apiVersion: v1
kind: Service
metadata:
  name: window-tinting-service
spec:
  type: LoadBalancer
  selector:
    app: window-tinting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
