name: Docker Build & Push to ECR

on:
  push:
    paths:
      - 'Dockerfile'
      - '**/*.cs'
      - '.github/workflows/app.yml'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 253490792199.dkr.ecr.us-east-2.amazonaws.com

    - name: Build Docker Image
      run: docker build -t window-tinting-app .

    - name: Tag and Push to ECR
      run: |
        docker tag window-tinting-app:latest 253490792199.dkr.ecr.us-east-2.amazonaws.com/window-tinting-app:latest
        docker push 253490792199.dkr.ecr.us-east-2.amazonaws.com/window-tinting-app:latest
